//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBranchSubZoneQuery
    {
        public int BankBranchID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankName { get; set; }
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public int SubZoneID { get; set; }
        public string SubZoneDescription { get; set; }
    }
}
