//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSettlement
    {
        public int WarehouseID { get; set; }
        public int CustomerID { get; set; }
        public int CashSettlementID { get; set; }
        public int TransactionNo { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> CashSettlementDate { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<System.DateTime> DeliveryChallanDate { get; set; }
        public Nullable<int> DeliveryChallanNumbers { get; set; }
        public Nullable<int> PassCodeChallan { get; set; }
        public Nullable<decimal> AgencyCommission { get; set; }
        public Nullable<decimal> TotalSpecialCharges { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CheckedByShipping { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public string RebateWillBeGivenWithOrder { get; set; }
        public string SpecialInstruction { get; set; }
        public Nullable<int> CashMemo { get; set; }
        public string SpecialNoteFromOrder { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<int> ProductRateID { get; set; }
        public string DayendFinished { get; set; }
        public Nullable<System.DateTime> DayendDay { get; set; }
        public Nullable<int> CustomerExecutiveID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string ReceiveRefundMemo { get; set; }
        public Nullable<decimal> DrinksAmount { get; set; }
        public Nullable<decimal> DrinksAmountPaid { get; set; }
        public Nullable<decimal> SecurityAmount { get; set; }
        public Nullable<decimal> SecurityAmountPaid { get; set; }
        public string IsBottleCreditGiven { get; set; }
        public string Promotional { get; set; }
        public string BurstRefund { get; set; }
        public string BurstNote { get; set; }
        public string CanceledChallan { get; set; }
        public string CancelReason { get; set; }
        public string InvoiceFromVATInvoiceNumber { get; set; }
        public Nullable<int> VATRateId { get; set; }
        public string VATChallanRequired { get; set; }
        public Nullable<decimal> FinishGoodsUnloadCharge { get; set; }
        public Nullable<decimal> EmptyReturnLoadCharge { get; set; }
        public Nullable<decimal> ReturnFGCharge { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CraeteDate { get; set; }
    }
}
