//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLedgerDetail
    {
        public int WarehouseID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<decimal> DrAmount { get; set; }
        public Nullable<decimal> CrAmount { get; set; }
        public string DebitCredit { get; set; }
        public string ReverseFlag { get; set; }
        public string RefNumber1 { get; set; }
        public Nullable<int> RefNumber { get; set; }
        public string Narration { get; set; }
        public string AdjustmentFlag { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
