//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryControl
    {
        public int SLNo { get; set; }
        public int CustomerID { get; set; }
        public int WarehouseID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public double RcvlAmnt { get; set; }
        public bool IsRcvl { get; set; }
        public System.DateTime IsRcvlBDate { get; set; }
        public System.DateTime IsRcvlEDate { get; set; }
        public int OutsDays { get; set; }
        public bool IsODays { get; set; }
        public System.DateTime IsODaysBDate { get; set; }
        public System.DateTime IsODaysEDate { get; set; }
        public double TransitAmnt { get; set; }
        public bool IsTrAmnt { get; set; }
        public System.DateTime IsTrAmntBDate { get; set; }
        public System.DateTime IsTrAmntEDate { get; set; }
        public double TransitCase { get; set; }
        public bool IsTrCase { get; set; }
        public System.DateTime IsTrCaseBDate { get; set; }
        public System.DateTime IsTrCaseEDate { get; set; }
        public int TransitDays { get; set; }
        public bool IsTrDays { get; set; }
        public System.DateTime IsTrDaysBDate { get; set; }
        public System.DateTime IsTrDaysEDate { get; set; }
        public double BCAmnt { get; set; }
        public bool IsBCAmnt { get; set; }
        public System.DateTime IsBCAmntBDate { get; set; }
        public System.DateTime IsBCAmntEDate { get; set; }
        public double TotalOutstanding { get; set; }
        public bool IsTotalOutstanding { get; set; }
        public System.DateTime IsTotalOutstandingBDate { get; set; }
        public System.DateTime IsTotalOutstandingEDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsBGurated { get; set; }
        public string Remarks { get; set; }
    }
}
