//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmptyMoveMaster
    {
        public int SLNo { get; set; }
        public int WarehouseID { get; set; }
        public int TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TotalEmpty { get; set; }
        public Nullable<decimal> TotalBox { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> ToWarehouse { get; set; }
        public string Status { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string VehicleNo { get; set; }
        public string LocationID { get; set; }
        public string BinNo { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> ConversionFactor { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FromWarehouse { get; set; }
        public Nullable<int> ReturnID { get; set; }
    }
}
