//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHelper
    {
        public int SL { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> HelperID1 { get; set; }
        public Nullable<int> HelperID2 { get; set; }
        public Nullable<int> HelperID3 { get; set; }
        public Nullable<int> HelperID4 { get; set; }
        public Nullable<int> DriverID1 { get; set; }
        public Nullable<int> DriverID2 { get; set; }
    }
}
