//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> SalesOrderNo { get; set; }
        public Nullable<int> Trip { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int CustomerID { get; set; }
        public int WarehouseID { get; set; }
        public int VehicleID { get; set; }
        public int SalesPersonID { get; set; }
        public int DriverID { get; set; }
        public Nullable<int> ChallanNumber { get; set; }
        public string ChallanCancel { get; set; }
        public Nullable<System.DateTime> DeliveryChallanDate { get; set; }
        public string Delivered { get; set; }
        public decimal SalesAmount { get; set; }
        public decimal SecurityAmount { get; set; }
        public decimal RebateAmount { get; set; }
        public decimal AgencyCommission { get; set; }
        public int ProductRateID { get; set; }
        public decimal SpecialCharge1Amount { get; set; }
        public decimal SpecialCharge2Amount { get; set; }
        public decimal SpecialCharge3Amount { get; set; }
        public int SpecialCharge1Type { get; set; }
        public int SpecialCharge2Type { get; set; }
        public int SpecialCharge3Type { get; set; }
        public string SpecialNote { get; set; }
        public string LoadSheetRemarks { get; set; }
        public string Cash { get; set; }
        public string IsCashSettlementPrepared { get; set; }
        public string DeliveredBy { get; set; }
        public Nullable<int> CashSettlementID { get; set; }
        public string CashSettlementPreparedBy { get; set; }
        public string ReadyForDelivery { get; set; }
        public string ReadyForDeliveryOptionGivenBy { get; set; }
        public string RebateWillBeGivenWithOrder { get; set; }
        public int OrderTypeID { get; set; }
        public string Transit { get; set; }
        public Nullable<int> CustomerExecutiveID { get; set; }
        public string Promotional { get; set; }
        public string Replacement { get; set; }
        public string InvoiceFromVATInvoiceNumber { get; set; }
        public int VATRateId { get; set; }
        public string VATChallanRequired { get; set; }
        public Nullable<decimal> FinishGoodsUnloadCharge { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string AdvanceOrder { get; set; }
    }
}
