//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderV
    {
        public int SalesOrderNO { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> OrderCase { get; set; }
        public Nullable<decimal> PlasticBox { get; set; }
        public System.DateTime SalesOrderDate { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    }
}
