//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderApprove
    {
        public int SL { get; set; }
        public int WarehouseID { get; set; }
        public int ApprovedID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Status { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string Approve2nd { get; set; }
        public Nullable<System.DateTime> Approve2ndDate { get; set; }
    }
}
