//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int CashSettlementID { get; set; }
        public int MoneyReceiptNo { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public System.DateTime CashSettlementDate { get; set; }
    }
}
