//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMItemDestroy
    {
        public int SL { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<System.DateTime> DestroyedDate { get; set; }
        public Nullable<int> POSMDestroyedItemID { get; set; }
        public string DestroyedFrom { get; set; }
        public Nullable<int> DQty { get; set; }
        public Nullable<int> DestroyedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
