//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMTemp
    {
        public int ItemID { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> OpeningBalenece { get; set; }
        public Nullable<int> TotalReceive { get; set; }
        public Nullable<int> TotalIssue { get; set; }
    }
}
