//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMStock
    {
        public int SL { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public int POSMItemID { get; set; }
        public Nullable<int> OnHandQty { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<int> IssuedQty { get; set; }
        public Nullable<int> ReturnedFreshQty { get; set; }
        public Nullable<int> ReturnedDefectedQty { get; set; }
        public Nullable<int> DestroyedQty { get; set; }
        public Nullable<int> OpeningQty { get; set; }
    }
}
