//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMItemReturn
    {
        public int SL { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnProductType { get; set; }
        public Nullable<int> ReturnItemID { get; set; }
        public Nullable<double> ReturnQty { get; set; }
        public Nullable<int> ReturnBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
