//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMReceive
    {
        public int SL { get; set; }
        public Nullable<int> GRNO { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public int SchemeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string SuppRefNo { get; set; }
        public Nullable<System.DateTime> SupplierRefDate { get; set; }
        public int POSItem { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string WarrentyPeriod { get; set; }
        public string WarrentyType { get; set; }
        public string RcvBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
