//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransactionDetail
    {
        public int SLNo { get; set; }
        public int TransactionNo { get; set; }
        public int WarehouseID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> PlantNo { get; set; }
        public Nullable<int> LineNoPlant { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal Quantity { get; set; }
        public int EmptyBottleQuantity { get; set; }
        public int PlasticBoxQuantity { get; set; }
        public int BurstBottleQuantity { get; set; }
        public int BreakageBottleQuantity { get; set; }
    }
}
