//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransaction
    {
        public int SLNo { get; set; }
        public int TransactionNo { get; set; }
        public int WarehouseID { get; set; }
        public int TransactionTypeID { get; set; }
        public Nullable<int> FromWarehouse { get; set; }
        public Nullable<int> ToWarehouse { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ReferenceNo { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string StoreLocation { get; set; }
    }
}
