//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransferNote
    {
        public int WarehouseID { get; set; }
        public int TransactionNo { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SLNo { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
