//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRateDetail
    {
        public int ProductRateID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal AlternateUnitPrice { get; set; }
        public decimal AgencyCommission { get; set; }
        public decimal AlternateAgencyCommission { get; set; }
        public decimal SecurityDeposit { get; set; }
        public decimal AlternateSecurityDeposit { get; set; }
        public decimal PlasticBoxSecurity { get; set; }
        public Nullable<decimal> MRPRate { get; set; }
        public string Status { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
