//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplaceManual
    {
        public int CustomerID { get; set; }
        public int ReplaceID { get; set; }
        public Nullable<int> MonthName { get; set; }
        public Nullable<int> NoLevel { get; set; }
        public Nullable<int> NoCrown { get; set; }
        public Nullable<int> NoCan { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<int> GivenMethod { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
