//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplaceDetail
    {
        public int SLNo { get; set; }
        public int ReplacementNo { get; set; }
        public int WarehouseID { get; set; }
        public int ProductID { get; set; }
        public int ReturnID { get; set; }
        public Nullable<decimal> AlternateQuantity { get; set; }
        public Nullable<decimal> PlasticBoxQuantity { get; set; }
        public Nullable<decimal> SubTotAmount { get; set; }
    }
}
