//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnmentDetail
    {
        public int ID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ReturnmentID { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Packsize { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> RebateQty { get; set; }
        public Nullable<decimal> RebatePlastic { get; set; }
        public Nullable<int> SchemeID { get; set; }
    }
}
