//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public int SalesPersonID { get; set; }
        public string SalesPersonName { get; set; }
        public Nullable<int> Suspended { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string updateBy { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
    }
}
