//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBatch
    {
        public int SLNo { get; set; }
        public int WarehouseID { get; set; }
        public int BatchNo { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> BatchRefNo { get; set; }
        public System.DateTime ManufacturDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> PlantNo { get; set; }
        public int PlantLineNo { get; set; }
        public decimal IssueQuantity { get; set; }
        public decimal ReceivedQty { get; set; }
        public decimal SalesQty { get; set; }
        public decimal MarketReturnQty { get; set; }
        public decimal ReplaceQty { get; set; }
        public decimal BurstQty { get; set; }
        public decimal BreakageQty { get; set; }
        public int AdjustQty { get; set; }
        public string Status { get; set; }
        public string WarehouseLocationCode { get; set; }
        public string BinNo { get; set; }
    }
}
