//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportAgencySetup
    {
        public int SlNo { get; set; }
        public int TAID { get; set; }
        public string TAName { get; set; }
        public string TAAdress { get; set; }
        public string TAMblNo { get; set; }
        public string TAEmail { get; set; }
        public string VATRegistrationInfo { get; set; }
        public Nullable<int> EligibleForCarringGoods { get; set; }
        public string Remarks { get; set; }
    }
}
