//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportQRData
    {
        public int SLNO { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public string Type { get; set; }
        public string VehicleType { get; set; }
        public string QRSLNo { get; set; }
        public int SLCount { get; set; }
        public System.DateTime QRGeneratingDate { get; set; }
        public int AgencyID { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNumber { get; set; }
        public int TruckCapacity { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public Nullable<System.DateTime> LoadingDateTime { get; set; }
        public Nullable<System.DateTime> InvoiceDateTime { get; set; }
        public Nullable<System.DateTime> CheckoutDateTime { get; set; }
        public byte[] QRImageIn { get; set; }
        public byte[] ORImageChallanTime { get; set; }
        public string FromWhere { get; set; }
        public Nullable<int> DeliveryChallanNumber { get; set; }
        public Nullable<int> SalesOrderNo { get; set; }
        public string EnteredBy { get; set; }
        public string ExitInfoEnteredBy { get; set; }
    }
}
