//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPepsi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public string VehicleDescription { get; set; }
        public string VehicleRegistrationNo { get; set; }
        public string VehicleCapacity { get; set; }
        public Nullable<System.DateTime> RegistrationRenewalDate { get; set; }
        public Nullable<System.DateTime> TaxTokenRenwalDate { get; set; }
        public Nullable<System.DateTime> InsurancePremiumPaymentDate { get; set; }
        public Nullable<System.DateTime> NextServicingDate { get; set; }
        public string OwnVehicle { get; set; }
        public int WarehouseID { get; set; }
    }
}
